Mar 21 10:46:05 ansible3 sshd[2391]: Accepted publickey for ansible from 192.168.10.10 port 60140 ssh2: RSA SHA256:NlojzC9QTD7O3CZWUnhESqsCxT/OpFFNi5SYMR3UYTI
Mar 21 10:46:05 ansible3 sshd[2391]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 10:46:05 ansible3 sudo[2593]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-rbnjhveohpxodijzgifyxccqcmxyyobf ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679363165.4851658-5658-106622788838783/AnsiballZ_setup.py
Mar 21 10:46:05 ansible3 sudo[2593]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 10:46:05 ansible3 sudo[2593]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 10:46:06 ansible3 sudo[2593]: pam_unix(sudo:session): session closed for user root
Mar 21 10:46:06 ansible3 sudo[2806]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-whnefvsnytntarttarfhxyxiuimwphtr ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679363166.6235957-5676-125330548618691/AnsiballZ_command.py
Mar 21 10:46:06 ansible3 sudo[2806]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 10:46:06 ansible3 sudo[2806]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 10:46:06 ansible3 sudo[2806]: pam_unix(sudo:session): session closed for user root
Mar 21 10:46:06 ansible3 sudo[2982]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-uqpfgqsxcfupypbridjjqbbuzhyljezf ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679363167.053534-5687-64639536788998/AnsiballZ_dnf.py
Mar 21 10:46:06 ansible3 sudo[2982]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 10:46:06 ansible3 sudo[2982]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 10:46:10 ansible3 sudo[2982]: pam_unix(sudo:session): session closed for user root
Mar 21 10:46:11 ansible3 sudo[3324]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wdqvsmwthhrcoqlpnqkrmxekypjaimzq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679363171.0864012-5696-224135485291093/AnsiballZ_systemd.py
Mar 21 10:46:11 ansible3 sudo[3324]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 10:46:11 ansible3 sudo[3324]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 10:46:11 ansible3 sudo[3324]: pam_unix(sudo:session): session closed for user root
Mar 21 10:47:11 ansible3 sshd[2394]: Received disconnect from 192.168.10.10 port 60140:11: disconnected by user
Mar 21 10:47:11 ansible3 sshd[2394]: Disconnected from user ansible 192.168.10.10 port 60140
Mar 21 10:47:11 ansible3 sshd[2391]: pam_unix(sshd:session): session closed for user ansible
Mar 21 10:47:30 ansible3 sshd[3376]: Accepted publickey for ansible from 192.168.10.10 port 39126 ssh2: RSA SHA256:NlojzC9QTD7O3CZWUnhESqsCxT/OpFFNi5SYMR3UYTI
Mar 21 10:47:30 ansible3 sshd[3376]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 10:47:31 ansible3 sudo[3578]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-bsysuxrdysrkhvhqyehzqwodpzsilycu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679363251.1508389-5763-280689798269959/AnsiballZ_setup.py
Mar 21 10:47:31 ansible3 sudo[3578]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 10:47:31 ansible3 sudo[3578]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 10:47:32 ansible3 sudo[3578]: pam_unix(sudo:session): session closed for user root
Mar 21 10:47:33 ansible3 sudo[3790]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ozwxadvwlyvqqwkgcvkqojeeulawyjwh ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679363253.1798987-5778-206657257317954/AnsiballZ_command.py
Mar 21 10:47:33 ansible3 sudo[3790]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 10:47:33 ansible3 sudo[3790]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 10:47:33 ansible3 sudo[3790]: pam_unix(sudo:session): session closed for user root
Mar 21 10:47:33 ansible3 sudo[3966]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zuijmnpjgiduvuzklluuiamjdonxjklf ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679363253.6236467-5791-41646524414252/AnsiballZ_dnf.py
Mar 21 10:47:33 ansible3 sudo[3966]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 10:47:33 ansible3 sudo[3966]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 10:47:35 ansible3 useradd[3978]: failed adding user 'mysql', exit code: 9
Mar 21 10:47:37 ansible3 sudo[3966]: pam_unix(sudo:session): session closed for user root
Mar 21 10:47:38 ansible3 sudo[4747]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ytajihggutrfewidxacqrazkmquwsdde ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679363258.3173883-5800-100790408595123/AnsiballZ_systemd.py
Mar 21 10:47:38 ansible3 sudo[4747]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 10:47:38 ansible3 sudo[4747]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 10:47:38 ansible3 sudo[4747]: pam_unix(sudo:session): session closed for user root
Mar 21 10:47:43 ansible3 sudo[5108]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vodlsmmxepndbutkqrrhbcmccxnhavbj ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679363263.6502802-5824-117730122211222/AnsiballZ_setup.py
Mar 21 10:47:43 ansible3 sudo[5108]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 10:47:43 ansible3 sudo[5108]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 10:47:44 ansible3 sudo[5108]: pam_unix(sudo:session): session closed for user root
Mar 21 10:47:44 ansible3 sudo[5320]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-mbamzynaepfdanyomqavsmjnxtytginu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679363264.678125-5835-10188893557280/AnsiballZ_command.py
Mar 21 10:47:44 ansible3 sudo[5320]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 10:47:44 ansible3 sudo[5320]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 10:47:44 ansible3 sudo[5320]: pam_unix(sudo:session): session closed for user root
Mar 21 10:47:45 ansible3 sudo[5496]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-hbdqxmbcorutpmgwboxuwmacbpllcqqr ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679363265.1139507-5846-75417533686883/AnsiballZ_dnf.py
Mar 21 10:47:45 ansible3 sudo[5496]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 10:47:45 ansible3 sudo[5496]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 10:47:47 ansible3 sudo[5496]: pam_unix(sudo:session): session closed for user root
Mar 21 10:47:48 ansible3 sudo[5672]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wmfpsfgmbxjxpavjsqbezkukbtvqidbr ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679363268.0117514-5857-172158605769650/AnsiballZ_systemd.py
Mar 21 10:47:48 ansible3 sudo[5672]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 10:47:48 ansible3 sudo[5672]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 10:47:48 ansible3 sudo[5672]: pam_unix(sudo:session): session closed for user root
Mar 21 10:48:48 ansible3 sshd[3379]: Received disconnect from 192.168.10.10 port 39126:11: disconnected by user
Mar 21 10:48:48 ansible3 sshd[3379]: Disconnected from user ansible 192.168.10.10 port 39126
Mar 21 10:48:48 ansible3 sshd[3376]: pam_unix(sshd:session): session closed for user ansible
Mar 21 10:57:11 ansible3 sshd[5786]: Accepted publickey for ansible from 192.168.10.10 port 52868 ssh2: RSA SHA256:NlojzC9QTD7O3CZWUnhESqsCxT/OpFFNi5SYMR3UYTI
Mar 21 10:57:11 ansible3 sshd[5786]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 10:57:12 ansible3 sudo[5988]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-utwmdmikfxmvfosacbxpeghykqoicgom ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679363832.2876785-6201-167688992341492/AnsiballZ_setup.py
Mar 21 10:57:12 ansible3 sudo[5988]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 10:57:12 ansible3 sudo[5988]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 10:57:12 ansible3 sudo[5988]: pam_unix(sudo:session): session closed for user root
Mar 21 10:57:13 ansible3 sudo[6200]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wflwavtkbzejvqerpzskzcimpxpcchah ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679363833.3166468-6216-165713793187800/AnsiballZ_systemd.py
Mar 21 10:57:13 ansible3 sudo[6200]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 10:57:13 ansible3 sudo[6200]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 10:57:14 ansible3 sudo[6200]: pam_unix(sudo:session): session closed for user root
Mar 21 10:57:15 ansible3 sudo[6387]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-iaoiqnmuefbgcybltxceszpxrrtcwytq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679363835.2065792-6225-201894894259693/AnsiballZ_dnf.py
Mar 21 10:57:15 ansible3 sudo[6387]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 10:57:15 ansible3 sudo[6387]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 10:57:17 ansible3 sudo[6387]: pam_unix(sudo:session): session closed for user root
Mar 21 10:58:17 ansible3 sshd[5789]: Received disconnect from 192.168.10.10 port 52868:11: disconnected by user
Mar 21 10:58:17 ansible3 sshd[5789]: Disconnected from user ansible 192.168.10.10 port 52868
Mar 21 10:58:17 ansible3 sshd[5786]: pam_unix(sshd:session): session closed for user ansible
Mar 21 12:43:08 ansible3 sshd[7773]: Accepted publickey for ansible from 192.168.10.10 port 47000 ssh2: RSA SHA256:NlojzC9QTD7O3CZWUnhESqsCxT/OpFFNi5SYMR3UYTI
Mar 21 12:43:08 ansible3 sshd[7773]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 12:43:10 ansible3 sshd[7776]: Received disconnect from 192.168.10.10 port 47000:11: disconnected by user
Mar 21 12:43:10 ansible3 sshd[7776]: Disconnected from user ansible 192.168.10.10 port 47000
Mar 21 12:43:10 ansible3 sshd[7773]: pam_unix(sshd:session): session closed for user ansible
Mar 21 14:56:52 ansible3 sshd[8965]: Accepted publickey for ansible from 192.168.10.10 port 53952 ssh2: RSA SHA256:NlojzC9QTD7O3CZWUnhESqsCxT/OpFFNi5SYMR3UYTI
Mar 21 14:56:52 ansible3 sshd[8965]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 14:56:53 ansible3 sudo[9167]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-asgvxqsnzkvnoosiedoqufgrxmaearrk ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378213.176584-17769-18613249172474/AnsiballZ_setup.py
Mar 21 14:56:53 ansible3 sudo[9167]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:56:53 ansible3 sudo[9167]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:56:53 ansible3 sudo[9167]: pam_unix(sudo:session): session closed for user root
Mar 21 14:56:55 ansible3 sudo[9380]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-zhllaudgmsyjdrrhlzppmoskzvibezpn ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378215.4498873-17829-76780575847810/AnsiballZ_dnf.py
Mar 21 14:56:55 ansible3 sudo[9380]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:56:55 ansible3 sudo[9380]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:56:58 ansible3 useradd[9393]: failed adding user 'mysql', exit code: 9
Mar 21 14:57:01 ansible3 sudo[9380]: pam_unix(sudo:session): session closed for user root
Mar 21 14:57:01 ansible3 sudo[10216]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-laleibnvrjgratjpagpimldvhvqolwpf ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378222.0589805-17829-199575131497/AnsiballZ_dnf.py
Mar 21 14:57:01 ansible3 sudo[10216]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:57:01 ansible3 sudo[10216]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:57:04 ansible3 sudo[10216]: pam_unix(sudo:session): session closed for user root
Mar 21 14:57:12 ansible3 sudo[10395]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-botizvhzugnflsphxfrjehbbihehmxjb ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378232.5364747-17913-120241989813052/AnsiballZ_get_url.py
Mar 21 14:57:12 ansible3 sudo[10395]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:57:12 ansible3 sudo[10395]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:57:12 ansible3 sudo[10395]: pam_unix(sudo:session): session closed for user root
Mar 21 14:57:13 ansible3 sudo[10572]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-atozuwyuutwvwceancmixpqpxzhfnayi ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378233.206908-17949-79533133149371/AnsiballZ_get_url.py
Mar 21 14:57:13 ansible3 sudo[10572]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:57:13 ansible3 sudo[10572]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:57:13 ansible3 sudo[10572]: pam_unix(sudo:session): session closed for user root
Mar 21 14:57:13 ansible3 sudo[10749]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-bfvlqbozfgmesrzdfcuktexgzsxptbyq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378233.7582836-17988-249662542480577/AnsiballZ_stat.py
Mar 21 14:57:13 ansible3 sudo[10749]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:57:13 ansible3 sudo[10749]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:57:13 ansible3 sudo[10749]: pam_unix(sudo:session): session closed for user root
Mar 21 14:57:14 ansible3 sudo[10894]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-xxvvmfwsptssbyrkyverpijigdepucml ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378233.7582836-17988-249662542480577/AnsiballZ_copy.py
Mar 21 14:57:14 ansible3 sudo[10894]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:57:14 ansible3 sudo[10894]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:57:14 ansible3 sudo[10894]: pam_unix(sudo:session): session closed for user root
Mar 21 14:57:14 ansible3 sudo[11071]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-qbfluyemtognymxgorrfonypkwyaspet ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378234.7117429-18052-248269531093357/AnsiballZ_stat.py
Mar 21 14:57:14 ansible3 sudo[11071]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:57:14 ansible3 sudo[11071]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:57:14 ansible3 sudo[11071]: pam_unix(sudo:session): session closed for user root
Mar 21 14:57:14 ansible3 sudo[11216]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-uiwwcgubzyjprerlerypffosefgeitta ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378234.7117429-18052-248269531093357/AnsiballZ_copy.py
Mar 21 14:57:14 ansible3 sudo[11216]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:57:14 ansible3 sudo[11216]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:57:15 ansible3 sudo[11216]: pam_unix(sudo:session): session closed for user root
Mar 21 14:57:15 ansible3 sudo[11393]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ozfjrhtvlpgqpcfkwkhqflspwzpaoocz ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378235.529593-18116-166725615488226/AnsiballZ_systemd.py
Mar 21 14:57:15 ansible3 sudo[11393]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:57:15 ansible3 sudo[11393]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:57:16 ansible3 sudo[11393]: pam_unix(sudo:session): session closed for user root
Mar 21 14:57:19 ansible3 sudo[11725]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-hlxqfslohdmrqllwattiqliqumglirsq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378239.5484712-18149-209969754694680/AnsiballZ_systemd.py
Mar 21 14:57:19 ansible3 sudo[11725]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 14:57:19 ansible3 sudo[11725]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 14:57:20 ansible3 sudo[11725]: pam_unix(sudo:session): session closed for user root
Mar 21 14:58:21 ansible3 sshd[8968]: Received disconnect from 192.168.10.10 port 53952:11: disconnected by user
Mar 21 14:58:21 ansible3 sshd[8968]: Disconnected from user ansible 192.168.10.10 port 53952
Mar 21 14:58:21 ansible3 sshd[8965]: pam_unix(sshd:session): session closed for user ansible
Mar 21 15:04:30 ansible3 sshd[11965]: Accepted publickey for ansible from 192.168.10.10 port 59956 ssh2: RSA SHA256:NlojzC9QTD7O3CZWUnhESqsCxT/OpFFNi5SYMR3UYTI
Mar 21 15:04:30 ansible3 sshd[11965]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 15:04:30 ansible3 sudo[12167]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-cukpvcxgkxnyrwlbdnktqgqwqrowkzij ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378670.4230254-18406-139888674344523/AnsiballZ_setup.py
Mar 21 15:04:30 ansible3 sudo[12167]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:04:30 ansible3 sudo[12167]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:04:31 ansible3 sudo[12167]: pam_unix(sudo:session): session closed for user root
Mar 21 15:04:32 ansible3 sudo[12388]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-essdlzylxdmhvhtmamgirzqaaqeiyufg ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378672.5896525-18467-78287579879816/AnsiballZ_dnf.py
Mar 21 15:04:32 ansible3 sudo[12388]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:04:32 ansible3 sudo[12388]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:04:35 ansible3 sudo[12388]: pam_unix(sudo:session): session closed for user root
Mar 21 15:04:35 ansible3 sudo[12564]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-sbwoxppqbqtlwefgjmawnscazoqwuvyr ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378675.5288765-18467-31345980765218/AnsiballZ_dnf.py
Mar 21 15:04:35 ansible3 sudo[12564]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:04:35 ansible3 sudo[12564]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:04:36 ansible3 sudo[12564]: pam_unix(sudo:session): session closed for user root
Mar 21 15:04:37 ansible3 sudo[12740]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-akuglwfulincbkkayivpuwtcfirnwmur ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378677.3374918-18504-139794220362613/AnsiballZ_get_url.py
Mar 21 15:04:37 ansible3 sudo[12740]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:04:37 ansible3 sudo[12740]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:04:37 ansible3 sudo[12740]: pam_unix(sudo:session): session closed for user root
Mar 21 15:04:37 ansible3 sudo[12917]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-nwimvdzlmmhftryypuvqzdxfxwcrmzpy ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378677.9251776-18525-74028735247318/AnsiballZ_stat.py
Mar 21 15:04:37 ansible3 sudo[12917]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:04:37 ansible3 sudo[12917]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:04:37 ansible3 sudo[12917]: pam_unix(sudo:session): session closed for user root
Mar 21 15:04:38 ansible3 sudo[13062]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-mtihjuhtxikhciatpbjkonoqdtypflqi ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378677.9251776-18525-74028735247318/AnsiballZ_copy.py
Mar 21 15:04:38 ansible3 sudo[13062]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:04:38 ansible3 sudo[13062]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:04:38 ansible3 sudo[13062]: pam_unix(sudo:session): session closed for user root
Mar 21 15:05:02 ansible3 sudo[13294]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ihhudetyqdzbslpxysevebutliriznnd ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378702.368042-18591-98115884217180/AnsiballZ_command.py
Mar 21 15:05:02 ansible3 sudo[13294]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:05:02 ansible3 sudo[13294]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:05:02 ansible3 sudo[13294]: pam_unix(sudo:session): session closed for user root
Mar 21 15:05:17 ansible3 sudo[13526]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wtsrnyetvdavausnzobsbcurcbmolilo ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378717.0001068-18643-231387434658835/AnsiballZ_setup.py
Mar 21 15:05:17 ansible3 sudo[13526]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:05:17 ansible3 sudo[13526]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:05:17 ansible3 sudo[13526]: pam_unix(sudo:session): session closed for user root
Mar 21 15:05:18 ansible3 sudo[13738]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-bqjmijvhzocijswuufbhpcokbsxkgqqq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378718.1942837-18687-78491559321751/AnsiballZ_get_url.py
Mar 21 15:05:18 ansible3 sudo[13738]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:05:18 ansible3 sudo[13738]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:05:18 ansible3 sudo[13738]: pam_unix(sudo:session): session closed for user root
Mar 21 15:05:18 ansible3 sudo[13915]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tpqeduuanvzvwmuxyfcqbdeshjsntiol ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378718.7498434-18710-66302790444557/AnsiballZ_stat.py
Mar 21 15:05:18 ansible3 sudo[13915]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:05:18 ansible3 sudo[13915]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:05:18 ansible3 sudo[13915]: pam_unix(sudo:session): session closed for user root
Mar 21 15:05:19 ansible3 sudo[14060]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-gopdwqzrhmqmehqvyxcgstuzdblchbzl ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378718.7498434-18710-66302790444557/AnsiballZ_copy.py
Mar 21 15:05:19 ansible3 sudo[14060]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:05:19 ansible3 sudo[14060]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:05:19 ansible3 sudo[14060]: pam_unix(sudo:session): session closed for user root
Mar 21 15:05:28 ansible3 sudo[14292]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-tnaljixmmbkdpggccfpvdzeboyzyvqcu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679378728.8789728-18754-67362942428872/AnsiballZ_command.py
Mar 21 15:05:28 ansible3 sudo[14292]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:05:28 ansible3 sudo[14292]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:05:28 ansible3 sudo[14292]: pam_unix(sudo:session): session closed for user root
Mar 21 15:06:29 ansible3 sshd[11968]: Received disconnect from 192.168.10.10 port 59956:11: disconnected by user
Mar 21 15:06:29 ansible3 sshd[11968]: Disconnected from user ansible 192.168.10.10 port 59956
Mar 21 15:06:29 ansible3 sshd[11965]: pam_unix(sshd:session): session closed for user ansible
Mar 21 15:13:11 ansible3 sshd[14393]: Accepted publickey for ansible from 192.168.10.10 port 40484 ssh2: RSA SHA256:NlojzC9QTD7O3CZWUnhESqsCxT/OpFFNi5SYMR3UYTI
Mar 21 15:13:11 ansible3 sshd[14393]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 15:13:12 ansible3 sudo[14595]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lnpsdqlbvgolgdlisuadufhrkidjybsa ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379191.93395-19195-156747349365308/AnsiballZ_setup.py
Mar 21 15:13:12 ansible3 sudo[14595]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:13:12 ansible3 sudo[14595]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:13:13 ansible3 sudo[14595]: pam_unix(sudo:session): session closed for user root
Mar 21 15:13:14 ansible3 sudo[14808]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-qhzcizbjigcxrmwdojazdsmnsmoqlwte ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379194.076495-19258-207167368302135/AnsiballZ_command.py
Mar 21 15:13:14 ansible3 sudo[14808]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:13:14 ansible3 sudo[14808]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:13:14 ansible3 sudo[14808]: pam_unix(sudo:session): session closed for user root
Mar 21 15:14:14 ansible3 sshd[14396]: Received disconnect from 192.168.10.10 port 40484:11: disconnected by user
Mar 21 15:14:14 ansible3 sshd[14396]: Disconnected from user ansible 192.168.10.10 port 40484
Mar 21 15:14:14 ansible3 sshd[14393]: pam_unix(sshd:session): session closed for user ansible
Mar 21 15:15:26 ansible3 sshd[14859]: Accepted publickey for ansible from 192.168.10.10 port 56968 ssh2: RSA SHA256:NlojzC9QTD7O3CZWUnhESqsCxT/OpFFNi5SYMR3UYTI
Mar 21 15:15:26 ansible3 sshd[14859]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 15:15:27 ansible3 sudo[15061]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-rsymvkiomdixevbzrqehmpelsgzeheen ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379327.3619444-19408-252023603212563/AnsiballZ_setup.py
Mar 21 15:15:27 ansible3 sudo[15061]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:15:27 ansible3 sudo[15061]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:15:29 ansible3 sudo[15061]: pam_unix(sudo:session): session closed for user root
Mar 21 15:15:29 ansible3 sudo[15274]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-fyrcxwwygsiogwyernlhvxwknwwttyea ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379329.527447-19469-10739737804838/AnsiballZ_command.py
Mar 21 15:15:29 ansible3 sudo[15274]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:15:29 ansible3 sudo[15274]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:15:29 ansible3 sudo[15274]: pam_unix(sudo:session): session closed for user root
Mar 21 15:15:30 ansible3 sudo[15450]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ermcubkzaoprahghlhzfqylyjcbsqfrv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379330.010131-19505-133067977583926/AnsiballZ_systemd.py
Mar 21 15:15:30 ansible3 sudo[15450]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:15:30 ansible3 sudo[15450]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:15:31 ansible3 sudo[15450]: pam_unix(sudo:session): session closed for user root
Mar 21 15:15:31 ansible3 sudo[15660]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-lhyixliqdsxvcwwawlaxcgtsvsahfxis ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679379332.001125-19541-198864172243925/AnsiballZ_dnf.py
Mar 21 15:15:31 ansible3 sudo[15660]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:15:31 ansible3 sudo[15660]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:15:34 ansible3 sudo[15660]: pam_unix(sudo:session): session closed for user root
Mar 21 15:16:35 ansible3 sshd[14862]: Received disconnect from 192.168.10.10 port 56968:11: disconnected by user
Mar 21 15:16:35 ansible3 sshd[14862]: Disconnected from user ansible 192.168.10.10 port 56968
Mar 21 15:16:35 ansible3 sshd[14859]: pam_unix(sshd:session): session closed for user ansible
Mar 21 15:49:36 ansible3 sshd[16423]: Accepted publickey for ansible from 192.168.10.10 port 42722 ssh2: RSA SHA256:NlojzC9QTD7O3CZWUnhESqsCxT/OpFFNi5SYMR3UYTI
Mar 21 15:49:36 ansible3 sshd[16423]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 15:49:36 ansible3 sudo[16625]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-egiyeqrcxzwikyknuypbustzcgtcwmcv ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381376.8160298-21039-147475381596770/AnsiballZ_setup.py
Mar 21 15:49:36 ansible3 sudo[16625]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:49:36 ansible3 sudo[16625]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:49:37 ansible3 sudo[16625]: pam_unix(sudo:session): session closed for user root
Mar 21 15:50:37 ansible3 sshd[16426]: Received disconnect from 192.168.10.10 port 42722:11: disconnected by user
Mar 21 15:50:37 ansible3 sshd[16426]: Disconnected from user ansible 192.168.10.10 port 42722
Mar 21 15:50:37 ansible3 sshd[16423]: pam_unix(sshd:session): session closed for user ansible
Mar 21 15:50:50 ansible3 sshd[16706]: Accepted publickey for ansible from 192.168.10.10 port 37190 ssh2: RSA SHA256:NlojzC9QTD7O3CZWUnhESqsCxT/OpFFNi5SYMR3UYTI
Mar 21 15:50:50 ansible3 sshd[16706]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 15:50:50 ansible3 sudo[16908]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-rqthomhcxrpalziawaxlpbzmygmfapxt ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381450.6267145-21234-204345390091704/AnsiballZ_setup.py
Mar 21 15:50:50 ansible3 sudo[16908]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:50:50 ansible3 sudo[16908]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:50:51 ansible3 sudo[16908]: pam_unix(sudo:session): session closed for user root
Mar 21 15:50:51 ansible3 sudo[17120]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dhkrdkdququgbkppovbygncudtopcmtg ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381451.7791872-21296-124179067634022/AnsiballZ_dnf.py
Mar 21 15:50:51 ansible3 sudo[17120]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:50:51 ansible3 sudo[17120]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:50:54 ansible3 groupadd[17130]: group added to /etc/group: name=postdrop, GID=90
Mar 21 15:50:54 ansible3 groupadd[17130]: group added to /etc/gshadow: name=postdrop
Mar 21 15:50:54 ansible3 groupadd[17130]: new group: name=postdrop, GID=90
Mar 21 15:50:54 ansible3 groupadd[17136]: group added to /etc/group: name=postfix, GID=89
Mar 21 15:50:54 ansible3 groupadd[17136]: group added to /etc/gshadow: name=postfix
Mar 21 15:50:54 ansible3 groupadd[17136]: new group: name=postfix, GID=89
Mar 21 15:50:54 ansible3 useradd[17143]: new user: name=postfix, UID=89, GID=89, home=/var/spool/postfix, shell=/sbin/nologin
Mar 21 15:50:54 ansible3 useradd[17143]: add 'postfix' to group 'mail'
Mar 21 15:50:54 ansible3 useradd[17143]: add 'postfix' to shadow group 'mail'
Mar 21 15:50:56 ansible3 sudo[17120]: pam_unix(sudo:session): session closed for user root
Mar 21 15:50:56 ansible3 sudo[18557]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-hqkvgjsotgqmdflwfylayzrvtvonfolt ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381456.618941-21317-117478194507516/AnsiballZ_dnf.py
Mar 21 15:50:56 ansible3 sudo[18557]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:50:56 ansible3 sudo[18557]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:50:59 ansible3 groupadd[18570]: group added to /etc/group: name=dovecot, GID=97
Mar 21 15:50:59 ansible3 groupadd[18570]: group added to /etc/gshadow: name=dovecot
Mar 21 15:50:59 ansible3 groupadd[18570]: new group: name=dovecot, GID=97
Mar 21 15:50:59 ansible3 useradd[18577]: new user: name=dovecot, UID=97, GID=97, home=/usr/libexec/dovecot, shell=/sbin/nologin
Mar 21 15:50:59 ansible3 groupadd[18585]: group added to /etc/group: name=dovenull, GID=974
Mar 21 15:50:59 ansible3 groupadd[18585]: group added to /etc/gshadow: name=dovenull
Mar 21 15:50:59 ansible3 groupadd[18585]: new group: name=dovenull, GID=974
Mar 21 15:50:59 ansible3 useradd[18592]: new user: name=dovenull, UID=975, GID=974, home=/usr/libexec/dovecot, shell=/sbin/nologin
Mar 21 15:51:00 ansible3 sudo[18557]: pam_unix(sudo:session): session closed for user root
Mar 21 15:51:00 ansible3 sudo[19363]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wykqkojhjappjqqexctbpgyggbixhsqr ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381461.0283098-21340-256987889964/AnsiballZ_get_url.py
Mar 21 15:51:00 ansible3 sudo[19363]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:51:00 ansible3 sudo[19363]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:51:01 ansible3 sudo[19363]: pam_unix(sudo:session): session closed for user root
Mar 21 15:51:01 ansible3 sudo[19540]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-rnongcqpawvqhegvkktwnpmihxenvqlq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381461.6446774-21359-242238064441187/AnsiballZ_systemd.py
Mar 21 15:51:01 ansible3 sudo[19540]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:51:01 ansible3 sudo[19540]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:51:02 ansible3 sudo[19540]: pam_unix(sudo:session): session closed for user root
Mar 21 15:51:02 ansible3 sudo[19825]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-dwsvetpkyhehuhebtvajwwymsqeknuht ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381462.844761-21385-75053169156626/AnsiballZ_systemd.py
Mar 21 15:51:02 ansible3 sudo[19825]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:51:02 ansible3 sudo[19825]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:51:03 ansible3 sudo[19825]: pam_unix(sudo:session): session closed for user root
Mar 21 15:51:09 ansible3 sudo[20103]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-nkqcfpwqvmpeoknnwbhxfigmbcxfnssu ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381469.841888-21420-59433097201043/AnsiballZ_command.py
Mar 21 15:51:09 ansible3 sudo[20103]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:51:09 ansible3 sudo[20103]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:51:10 ansible3 sudo[20103]: pam_unix(sudo:session): session closed for user root
Mar 21 15:51:15 ansible3 sudo[20335]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-acltfhwbietjcilazjmcjzzjguislomk ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381475.8069506-21459-212874164219837/AnsiballZ_command.py
Mar 21 15:51:15 ansible3 sudo[20335]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:51:15 ansible3 sudo[20335]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:51:16 ansible3 sudo[20335]: pam_unix(sudo:session): session closed for user root
Mar 21 15:52:16 ansible3 sshd[16709]: Received disconnect from 192.168.10.10 port 37190:11: disconnected by user
Mar 21 15:52:16 ansible3 sshd[16709]: Disconnected from user ansible 192.168.10.10 port 37190
Mar 21 15:52:16 ansible3 sshd[16706]: pam_unix(sshd:session): session closed for user ansible
Mar 21 15:55:10 ansible3 sshd[20403]: Accepted publickey for ansible from 192.168.10.10 port 48734 ssh2: RSA SHA256:NlojzC9QTD7O3CZWUnhESqsCxT/OpFFNi5SYMR3UYTI
Mar 21 15:55:10 ansible3 sshd[20403]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 15:55:10 ansible3 sudo[20605]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-nfqrlrhqcnhjdqxrfmrbisnseucycfbg ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381710.7702847-21775-150496865337347/AnsiballZ_setup.py
Mar 21 15:55:10 ansible3 sudo[20605]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:55:10 ansible3 sudo[20605]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:55:12 ansible3 sudo[20605]: pam_unix(sudo:session): session closed for user root
Mar 21 15:55:12 ansible3 sudo[20817]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-wzlumwgkcwnfsvamtheyqmbiljjrwgrl ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381712.9356847-21837-163355437324693/AnsiballZ_systemd.py
Mar 21 15:55:12 ansible3 sudo[20817]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:55:12 ansible3 sudo[20817]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:55:13 ansible3 sudo[20817]: pam_unix(sudo:session): session closed for user root
Mar 21 15:55:13 ansible3 sudo[21036]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-qpbaqpvgarxtcqvuuczxfdnvkdpsprgt ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381713.7904892-21837-92031242653749/AnsiballZ_systemd.py
Mar 21 15:55:13 ansible3 sudo[21036]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:55:13 ansible3 sudo[21036]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:55:15 ansible3 sudo[21036]: pam_unix(sudo:session): session closed for user root
Mar 21 15:55:15 ansible3 sudo[21246]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ijkxgfcyuvevkwfchjhdodjmpyyyotts ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381715.5036237-21901-43051972896826/AnsiballZ_dnf.py
Mar 21 15:55:15 ansible3 sudo[21246]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:55:15 ansible3 sudo[21246]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:55:17 ansible3 sudo[21246]: pam_unix(sudo:session): session closed for user root
Mar 21 15:56:06 ansible3 sudo[22002]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-ymscuhluezdofpxxjzrxbwdlazpguaos ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679381767.0062897-21948-169432332809640/AnsiballZ_command.py
Mar 21 15:56:06 ansible3 sudo[22002]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 15:56:06 ansible3 sudo[22002]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 15:56:07 ansible3 sudo[22002]: pam_unix(sudo:session): session closed for user root
Mar 21 15:57:07 ansible3 sshd[20406]: Received disconnect from 192.168.10.10 port 48734:11: disconnected by user
Mar 21 15:57:07 ansible3 sshd[20406]: Disconnected from user ansible 192.168.10.10 port 48734
Mar 21 15:57:07 ansible3 sshd[20403]: pam_unix(sshd:session): session closed for user ansible
Mar 21 16:59:46 ansible3 sshd[22574]: Accepted publickey for ansible from 192.168.10.10 port 34564 ssh2: RSA SHA256:NlojzC9QTD7O3CZWUnhESqsCxT/OpFFNi5SYMR3UYTI
Mar 21 16:59:46 ansible3 sshd[22574]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 16:59:47 ansible3 sudo[22776]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-sjrjqrphpfleuldfjbxefsigvvirmaym ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679385587.323269-23788-197367347844423/AnsiballZ_setup.py
Mar 21 16:59:47 ansible3 sudo[22776]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:59:47 ansible3 sudo[22776]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:59:48 ansible3 sudo[22776]: pam_unix(sudo:session): session closed for user root
Mar 21 16:59:51 ansible3 sudo[22988]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-twteutgdcjnkcaruzxvrpwszfmngwllq ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679385591.5666978-23849-78940096842470/AnsiballZ_slurp.py
Mar 21 16:59:51 ansible3 sudo[22988]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 16:59:51 ansible3 sudo[22988]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 16:59:51 ansible3 sudo[22988]: pam_unix(sudo:session): session closed for user root
Mar 21 17:00:51 ansible3 sshd[22577]: Received disconnect from 192.168.10.10 port 34564:11: disconnected by user
Mar 21 17:00:51 ansible3 sshd[22577]: Disconnected from user ansible 192.168.10.10 port 34564
Mar 21 17:00:51 ansible3 sshd[22574]: pam_unix(sshd:session): session closed for user ansible
Mar 21 17:01:17 ansible3 sshd[23062]: Accepted publickey for ansible from 192.168.10.10 port 38400 ssh2: RSA SHA256:NlojzC9QTD7O3CZWUnhESqsCxT/OpFFNi5SYMR3UYTI
Mar 21 17:01:17 ansible3 sshd[23062]: pam_unix(sshd:session): session opened for user ansible by (uid=0)
Mar 21 17:01:17 ansible3 sudo[23264]: ansible : TTY=pts/0 ; PWD=/home/ansible ; USER=root ; COMMAND=/bin/sh -c echo BECOME-SUCCESS-vturrhctwpdigawhhecwwqrmekrymcki ; /usr/libexec/platform-python /home/ansible/.ansible/tmp/ansible-tmp-1679385677.655044-23992-256525463504583/AnsiballZ_setup.py
Mar 21 17:01:17 ansible3 sudo[23264]: pam_systemd(sudo:session): Cannot create session: Already running in a session or user slice
Mar 21 17:01:17 ansible3 sudo[23264]: pam_unix(sudo:session): session opened for user root by ansible(uid=0)
Mar 21 17:01:18 ansible3 sudo[23264]: pam_unix(sudo:session): session closed for user root
